# Generated by Django 4.2.7 on 2025-06-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='glb_file',
            field=models.FileField(blank=True, help_text='Upload GLB file for 3D model (for web viewing)', null=True, upload_to='dishes/3d_models/glb/'),
        ),
        migrations.AddField(
            model_name='dish',
            name='has_3d_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='usdz_file',
            field=models.FileField(blank=True, help_text='Upload USDZ file for 3D model (for iOS AR viewing)', null=True, upload_to='dishes/3d_models/usdz/'),
        ),
    ]
