# Generated by Django 4.2.7 on 2025-06-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0002_dish_glb_file_dish_has_3d_model_dish_usdz_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_vegetarian',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], default='non_veg', max_length=10),
        ),
    ]
