# Generated by Django 4.2.7 on 2025-06-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0003_dish_is_vegetarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ar_views',
            field=models.PositiveIntegerField(default=0, verbose_name='AR Views'),
        ),
        migrations.AddField(
            model_name='dish',
            name='model_3d_views',
            field=models.PositiveIntegerField(default=0, verbose_name='3D Model Views'),
        ),
    ]
