# Generated by Django 4.2.7 on 2025-06-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0004_dish_ar_views_dish_model_3d_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(related_name='dishes', to='menu_management.category'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_dishes', to='menu_management.category'),
        ),
    ]
